### ISSUE TITLE
Validate address

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/massa-as-sdk#229]
**Describe the bug**
Currently validate address in vm-mock does not match the way the core validate an address.

**Comment by Ben-Rey** [comment]
@sydhds @Leo-Besancon Do you have an idea on how I could validate a address in js and be as close as possible to the way it is done in rust ?

**Comment by Leo-Besancon** [comment]
Hi @Ben-Rey! So I assume because it's regarding a vm-mock you can't just call an ABI :p. In that case I think you'll have to handle the first characters manually (checking AU / AS prefix), and then use a library to decode the base58check?
For example, the [bitcoinjs/bs58check](https://github.com/bitcoinjs/bs58check/blob/master/base.js) repo has a decode function that checks that the checksum of the data you want to decode is valid.

Once it's done, you still may need to verify the version bytes from decoded data.

**Comment by Ben-Rey** [comment]
> Hi @Ben-Rey! So I assume because it's regarding a vm-mock you can't just call an ABI :p. In that case I think you'll have to handle the first characters manually (checking AU / AS prefix), and then use a library to decode the base58check? For example, the [bitcoinjs/bs58check](https://github.com/bitcoinjs/bs58check/blob/master/base.js) repo has a decode function that checks that the checksum of the data you want to decode is valid.
> 
> Once it's done, you still may need to verify the version bytes from decoded data.

Thanks !
