### ISSUE TITLE
Explain the difference between Storage and OpDatastore

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-as-sdk#246]
Documentation [here](https://github.com/massalabs/massa-as-sdk/blob/main/assembly/std/op-datastore/index.ts#L2) is should be completed with a why explaination

**Comment by Ben-Rey** [comment]
@sydhds could you give us an explanation of what is the operation datastore ?

**Comment by gregLibert** [comment]
Or maybe @Eitu33 can help us on this :thinking:

**Comment by Eitu33** [comment]
The operation datastore is a concept that is only present in the `ExecuteSC` operations (see `massa/massa-models/operation.rs`):
```rust
ExecuteSC {
    /// Smart contract bytecode.
    data: Vec<u8>,
    /// The maximum amount of gas that the execution of the contract is allowed to cost.
    max_gas: u64,
    /// A key-value store associating a hash to arbitrary bytes
    #[serde_as(as = "Vec<(_, _)>")]
    datastore: Datastore,
},
```
Here the `datastore` field is what we refer to when we speak about "operation datastore". It allows you to send a table of keys and values (same format as the persistent datastore), that will be taken into consideration when running the `ExecuteSC` operation, and that will not persist after that execution.

This can be useful to set initialization values such as ephemeral parameters and in a deployer SC case, bytecode corresponding to smart contracts that we would want to deploy. That way what you could have generic deployers that use the operation datastore instead of writing the smart contract bytes directly into the deployer.
