### ISSUE TITLE
Improve doc

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-as-sdk#57]
At least the following action needs to be covered:
- [x] List all functions with short intro to each function (JSdoc generated ?)
- [ ] Improve sendMessage documentation
- [x] activate a stricter linter for jsdoc in all of our code
- [x] deploy the html generated website to massa OVH server like the sc-playground under a subdomain of massa.net.

# QA
Doc hosted at https://as-sdk.docs.massa.net/

**Comment by ASAPSegfault** [comment]
This may be of interest to generate markdown from JSDoc : 
https://www.npmjs.com/package/jsdoc-to-markdown

**Comment by 0xMazout** [comment]
If it's validated JSDOC generated i take the follow

**Comment by 0xMazout** [comment]
At this moment , i will just try to ship a poc of : 
JSDOC generated using jsdoc-to-markdown and uploaded on netlify to see if we have something interesting 
Then in second time focus on update the doc to fit with the format

**Comment by 0xMazout** [comment]
As we are using Assembly Script this is the lists of package which are not working with AS : 

**https://www.npmjs.com/package/jsdoc-to-markdown** : KO only working with Javascript
**https://github.com/SoftwareBrothers/better-docs** :  KO Working with Typescript but need a ts.config file and when you give him. Big problems with compilators, normal we use AS 
**https://stackoverflow.com/questions/51720894/is-there-any-way-to-use-jsdoc-with-ts-files-maybe-transpile-with-babel-the** : KO The three method explained here doesn't work too because of AS.

I really don't understand why Compilation is involved in all of this stuffs , instead of just read the jsdoc and display it as a markdown but i won't surrend ! I Think i need a simpler plugins to manage this.
I'm actually trying to make it with original markdown system from JsDoc configured with typescript  but it's actually not working

**Comment by 0xMazout** [comment]
https://github.com/jaydenseric/jsdoc-md : KO don't recognize any of our JSdoc on .Ts files , (in case our jsdoc was broken I'm using their example and it didn't work too )

![Image](https://user-images.githubusercontent.com/10938862/209651820-02729613-bbc8-413b-80ff-a7afb85194db.png)

![Image](https://user-images.githubusercontent.com/10938862/209651870-777fb00d-88f5-4bad-99ae-a752737823e5.png)

**Comment by 0xMazout** [comment]
**We discussed about how Near is using it because they use AS too** : 
_Near don't use JSDOC and don't generate their markdown and docs throught the code._

**We discussed about ask on Assembly Script Discord** if they have solutions i readed lots of topics about JSDOC
 _and the main contributors of AS are doing lobbying against the pr related to JSDoc in AS ._ 

Now i will try to ask personnaly on AS discord and to throw the bottle to the sea and try to find a stupid package which job is only reading the doc and give me a markdown or html or something like this

**Comment by 0xMazout** [comment]
Looking on this thread : https://www.reddit.com/r/typescript/comments/vy1ew0/recommend_a_ts_documentation_generator/
To find a solution :
**https://github.com/ui-js/grok : KO , using TypeDoc. But could be our answer and the result is great :'(**

**Comment by 0xMazout** [comment]
https://discord.com/channels/721472913886281818/1057250855595806761 Link of the Bottle

**Comment by 0xMazout** [comment]
This is to have a trace about the status and discussion we had about this subject with @longgamma-massa 

I have done lots of tests of different libraries , read lots of PR and topics on discord and reddit, then i have put a question on discord to ask if someone is doing what we want. 

At this moment no one on the web is doing the first phase of the process which is : 
Generate (markdown or html) from JsDoc commentary in Assembly Script files. 

And the critical part is the Assembly Script files because it's not hard to generate jsdoc commentary from Javascript or Typescript but we are using Assembly Script and there is a small percentage of devs who are interested in Assembly Script so there is no tools to doing what we want. 

But we can fork an external lib and derive the type of code they can use , to maybe fit with Assembly Script. 

After a call with @Thykof  we have identified an hypothetical way to solve the problem.
Indeed the technical problem comes from the parser of the tools we want to use. The parser is the reader of the code 

But we have seen another tools doing the same thing we want to do : Prettier which is a popular tool is not working with Assembly Script and a guy did a fork of prettier before prettier receive the code ( in assembly script) and read it he change the format to fit with what is needed

But we have two problems :

a) First , this is really deep we are forking a library using another fork with the faith of this will be the right way to do it .
b) It may take some times. for sure we won't have result in two days. There is lots of possible wrong direction we can go in and we are not sure of what we are doing. Maybe the problem is more deeper than the parser . This libraries are not small libraries 

So this is two way to see this : 
- Take the time to work on this and try to make it work 
or
- See if we really need this in the future , and do it in another time

Maybe we can ask a point of view from @gregLibert  what do you think about it .

I have lots of informations and libraries which can be good to use but we need to work on them for sure

my opinion : At this moment i spent two days to test and have informations on Jsdoc and Typedoc and things like that i think we can stop the task. Focus on have a good Readme made manually , improve the linter of our Jsdoc and talk about if we really need this kind of process at this stage of the company (for sure it should be a good process to have but the time to invest can be huge and the tunnel effect can be big too)

**Comment by gregLibert** [comment]
To test it:
- go in the PR branch
- execute `npm run doc`
- open the index.html file located in the docs/documentation/html/ directory
- start testing

**Comment by longgamma-massa** [comment]
> To test it:
> 
> * go in the PR branch
> * execute `npm run doc`
> * open the index.html file located in the docs/documentation/html/ directory
> * start testing

Seems good for start. If we can modify the font style to Massa's it would be great. The rest I checked and seems ok.

**Comment by Thykof** [comment]
documentation linting and generation are well set up, now we need more specification on the output of the doc: where to put the html generated website? @longgamma-massa  @gregLibert

**Comment by gregLibert** [comment]
> documentation linting and generation are well set up, now we need more specification on the output of the doc: where to put the html generated website? @longgamma-massa @gregLibert

What about using Github pages ?

**Comment by 0xMazout** [comment]
Github Pages can be a good solution.

We just need to create a repo to host our release  docs package for each repo 

Then at each update on main the website should be updated to 

So our process can be :
a) at each Milestone or Release on the project, launch process generate docs website 
b) push to main release doc repo, the docs website last release
c) Website should be updated

Replicate this on each repo with a doc hosted needed

**Comment by Thykof** [comment]
keep in mind that Github page will generate a website at https://massalabs.github.io so the scope will be Massa as a whole, not only sc development. GitHub Page host one website per account or per organization. 

Note that it is possible to add a CNAME to use for example domain sc-docs.massa.net (https://stackoverflow.com/a/66354977/5903242). 

In addition, I am not fan of committing generated code. With Github page, I haven't seen yet another way than committing the website source code. The website source code will be generated by the repo massa-as-sdk CI. We need to find a way that the CI publish into our new repos `sc-docs`, this could be done by a script doing a git commit and git push into it.

But how to handle multiple repos (massa-as-sdk, as-types...) pushing into one repo (massalabs.github.io)? We will need an `index.html` that list every npm packages we have and one folder per packages. Then every repo will have a CI that update its folder.

Example for repo `as` and package `as-types`:
- `index.htm` contains a list: as-types, as-proba, massa-as-sdk
- `as` CI generate doc for as-types and as-proba
- the CI of as-types:
  - generate html documentation
  - clone the repo `sc-docs`, move the generated html doc into the right folder: /as-types
  - git push origin main
  - this will update the github page hosting

To conclude, I would rather look for a solution to host our assembly script smart-contract documentation into an external hosting provider and having a CI in each repo that

1) genreate the documentation in html format
2) deploy/publish it into the hosting provider (netlify for example)
3) serve it at massa-as-sdk-doc.massa.net and as-types-docs.massa.net for instance.

**Comment by longgamma-massa** [comment]
@Thykof do we have enough votes?

**Comment by Thykof** [comment]
Yes we do, I have update the proposal 3

**Comment by Thykof** [comment]
List of all folder in our server:

/var/wwww/type-doc/massa-as-sdk
/var/wwww/type-doc/massa-as-types
/var/wwww/type-doc/massa-as-proba
/var/wwww/type-doc/massa-web3
/var/wwww/type-doc/sc-deployer
/var/wwww/type-docs/smart-contracts 
/var/wwww/type-doc/as-transformer

**Comment by Thykof** [comment]
doc is now hosted at https://as-sdk.docs.massa.net/

**Comment by longgamma-massa** [comment]
@Thykof This issue is closed but in CR. Should I check anything?

**Comment by Thykof** [comment]
This issue is linked to an opened https://github.com/massalabs/massa-as-sdk/pull/134

so I reopen this issue and keep it in code review

**Comment by longgamma-massa** [comment]
@Thykof what about the second checkbox 'improve sendmessage'? Is it also done?

**Comment by Thykof** [comment]
No, I am asking core team

cc @AurelienFT

**Comment by Thykof** [comment]
Here is the explanation for sendMessage:

```
The goal of send message is to send a message (so smart) in the future that will be executed as soon as possible after the start period but not after the end period. This message allow you to make executions in the future and they are executed deterministically on all nodes. The execution is made "as soon as possible" because there is a priority on messages and a limit of messages possibly executed on each slot so if you send a low amount of fee then your message could possibly not executed directly at the first slot of the slot period. And if all of the slots of your period have a huge load of messages with more fee than you then it's possible that your message is never executed.

Also there is an optional filter on message that add a new condition on the trigger instead of : "as soon as possible in this range" it becomes "as soon as possible after this field has been update in the state in this range".
So you can pass as parameter an address and also an optional datastore key.
If you pass only an address then the message will be executed only after : "we are in the range and a change has happens during this range on the address" (possibly balance etc). If you add a datastore key in the condition : "we are in the range and a change has happens during this range on the address at that datastore key".
Without condition it's just : "we are in the range"


```
